[features]
seeds = false
skip-lint = false
[programs.localnet]
luxhaus = "DcPTwPTmFrmmVEH8nb9VzaU8NX5fAJZWBhCBD4dxBCPi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/sina/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
